language: python
python:
  - "3.6"
before_install:
  - "export BOTO_CONFIG=/dev/null" # https://github.com/travis-ci/travis-ci/issues/7940
install:
  - "pip install pipenv"
  - "pipenv install --dev"
script:
  - "black --check ssmenv test"
  - "pytest --cov=ssmenv --cov-report term test -vv"
after_success:
  - coveralls
